# Generated by Django 4.0.4 on 2022-04-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='post_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
