# Generated by Django 4.0.4 on 2022-05-23 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_contactformmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmodel',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
